"""Add unique constraint for provider and geojson

Revision ID: 1ffdc6a8685f
Revises: 
Create Date: 2024-10-20 21:02:53.751202

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1ffdc6a8685f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_email'), 'providers', ['email'], unique=False)
    op.create_index(op.f('ix_providers_name'), 'providers', ['name'], unique=False)
    op.create_index(op.f('ix_providers_phone_number'), 'providers', ['phone_number'], unique=False)
    op.create_table('service_areas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('geojson', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('geojson_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_id', 'geojson_hash', name='uq_provider_geojson')
    )
    op.create_index('idx_service_areas_geojson', 'service_areas', ['geojson'], unique=False, postgresql_using='gist')
    op.create_index('ix_service_area_geojson', 'service_areas', ['geojson'], unique=False, mysql_prefix='SPATIAL')
    op.create_index(op.f('ix_service_areas_geojson_hash'), 'service_areas', ['geojson_hash'], unique=False)
    op.create_index(op.f('ix_service_areas_name'), 'service_areas', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_areas_name'), table_name='service_areas')
    op.drop_index(op.f('ix_service_areas_geojson_hash'), table_name='service_areas')
    op.drop_index('ix_service_area_geojson', table_name='service_areas', mysql_prefix='SPATIAL')
    op.drop_index('idx_service_areas_geojson', table_name='service_areas', postgresql_using='gist')
    op.drop_table('service_areas')
    op.drop_index(op.f('ix_providers_phone_number'), table_name='providers')
    op.drop_index(op.f('ix_providers_name'), table_name='providers')
    op.drop_index(op.f('ix_providers_email'), table_name='providers')
    op.drop_table('providers')
    # ### end Alembic commands ###
